### ISSUE TITLE
Update date instead of unpublish

### ISSUE THREAD

**Issue by bronzdoc** [ombulabs/blogcop#2]
Blogcop should update the date then create a PR instead of a PR to unpublish the post

@lubc what you think?

**Comment by etagwerker** [comment]
@bronzdoc The goal of `blogcop` is to force you to review and update the article with recent information. If there is nothing to be updated, I don't know if this is a good idea.

**Comment by bronzdoc** [comment]
Ahh I see! in that case I'll close this issue lol
